/**
 * whale-map.md generator (P1⑦): one section per module — its header-comment
 * summary + every top-level function name — so an Agent (or human) can
 * locate "which module, which function" before opening src/. Regenerated by
 * build-whale.js on EVERY build, so it can never drift from the source.
 *
 * Usage: required (and invoked) by build-whale.js; also runnable directly:
 *   node scripts/generate-map.js
 */
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const manifestModule = require('../whale-manifest.js');

function generateMap() {
	const lines = [
		'# 🐋 whale.js 函数导航（构建时自动生成，勿手改）',
		'',
		'> 由 node build-whale.js 产出：每个模块的职责（取文件头注释首段）与顶层函数清单。',
		'> 改代码前先在这里定位模块，再进 src/ 对应文件；改完重新构建本表自动更新。',
		'',
		'共 ' + manifestModule.MANIFEST.length + ' 个模块（构建产物为单文件 IIFE，全部模块共享同一作用域）。',
		'',
	];
	manifestModule.MANIFEST.forEach(function (mod) {
		const src = fs.readFileSync(path.join(ROOT, mod.file), 'utf8');
		const badge = mod.inline ? '' : '（行切片）';
		lines.push('## **' + mod.file + '**' + badge);
		lines.push('');
		const head = /\/\*\*([\s\S]*?)\*\//.exec(src);
		if (head) {
			const summary = head[1].split('\n').map(function (l) { return l.replace(/^\s*\*\s?/, ''); }).join(' ').trim();
			if (summary) lines.push('> ' + summary.slice(0, 300));
			lines.push('');
		}
		const fnRe = /^\tfunction\s+([A-Za-z_$][\w$]*)\s*\(/gm;
		const varFnRe = /^\tvar\s+([A-Za-z_$][\w$]*)\s*=\s*function/gm;
		const names = [];
		let m;
		while ((m = fnRe.exec(src))) names.push('**' + m[1] + '()**');
		while ((m = varFnRe.exec(src))) names.push('**' + m[1] + '()**');
		if (names.length) {
			lines.push(names.join(' · '));
			lines.push('');
		}
	});
	const out = path.join(ROOT, 'whale-map.md');
	fs.writeFileSync(out, lines.join('\n'));
	return out;
}

if (require.main === module) {
	console.log('whale-map.md written:', generateMap());
}

module.exports = generateMap;
